version: '3.8'

services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      - POSTGRES_DB=gym_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=13274  # Use a simple password for local Docker dev
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  backend:
    build: ./gym_admin_backend   # Tells Docker where to find your new Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./gym_admin_backend:/app # Syncs your laptop files to the container instantly
    environment:
      # This leverages the dj-database-url package you installed earlier!
      - DATABASE_URL=postgres://postgres:13274@db:5432/gym_db
    depends_on:
      - db

volumes:
  postgres_data: