# Generated by Django 6.0.2 on 2026-02-18 08:41

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=16, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?\\d{7,15}$')])),
                ('email', models.EmailField(max_length=254, null=True, unique=True)),
                ('membership_type', models.CharField(choices=[('basic', 'Basic'), ('vip', 'VIP'), ('premium', 'Premium')], default='basic', max_length=20)),
                ('total_cash_paid', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RecentPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('payment_type', models.CharField(choices=[('card', 'Card'), ('cash', 'Cash'), ('upi', 'UPI')], default='cash', max_length=20)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recentPayment', to='members.member')),
            ],
        ),
    ]
