# Generated by Django 6.0.2 on 2026-02-18 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('plan_price', models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name='member',
            name='membership_type',
        ),
        migrations.AddField(
            model_name='member',
            name='membership_plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='members.membershipplan'),
        ),
    ]
