# Generated by Django 6.0.2 on 2026-02-18 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_membershipplan_remove_member_membership_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recentpayment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
