# Generated by Django 6.0.2 on 2026-02-20 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_recentpayment_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='total_cash_paid',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
