# Generated by Django 6.0.2 on 2026-03-06 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_recentpayment_membership_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recentpayment',
            name='membership_start_date',
            field=models.DateField(),
        ),
    ]
