# Generated by Django 6.0.2 on 2026-03-06 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0009_alter_recentpayment_membership_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recentpayment',
            name='membership_start_date',
        ),
        migrations.AddField(
            model_name='member',
            name='membership_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
