# Generated by Django 6.0.2 on 2026-03-06 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0010_remove_recentpayment_membership_start_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='membership_start_date',
            field=models.DateField(),
        ),
    ]
