# Generated by Django 6.0.2 on 2026-03-06 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0011_alter_member_membership_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('due', 'Due'), ('expired', 'Expired')], default='active', max_length=20),
        ),
    ]
