# Generated by Django 6.0.2 on 2026-03-07 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0012_member_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='total_cash_paid',
            field=models.FloatField(blank=True, default=0.0),
        ),
    ]
