# Generated by Django 6.0.2 on 2026-03-07 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0013_alter_member_total_cash_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='status',
        ),
    ]
