# Generated by Django 6.0.2 on 2026-03-14 18:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0015_alter_attendance_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='access_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
    ]
