# Generated by Django 6.0.2 on 2026-03-14 18:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0016_member_access_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='access_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
