# Generated by Django 6.0.2 on 2026-04-07 15:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0019_alter_attendance_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recentpayment',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
